---
title: "Data Science Project"
author: "Kristian Bjerke"
date: "24/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

library(dplyr)
library(ggplot2)
library(tidyverse)
library(gapminder)
library(gganimate)
library(hrbrthemes) # ikke sikker på om denne trenger å være med 
library(png)
library(gifski)
library(magick)
library(broom)
library(plotly)
library(crosstalk)
library(R2HTML)
packageVersion("plotly")


```

```{r}
#Laster opp og rydder HDI filen
hdi <- read.csv("human-development-index.csv")
hdi <- rename(hdi, "Country" = "Entity")
hdi <- rename(hdi, "Value" = "X..0.1..higher.values.are.better..")
hdi <- hdi[ ,-2]
```

```{r}
#Laster opp og rydder renewable energy filen

energy <- read.csv("modern-renewable-energy-consumption.csv")
energy <- rename(energy, "Country" = "Entity")
energy <- rename(energy, "Hydro" = "Hydropower..terawatt.hours.")
energy <- rename(energy, "Wind" = "Wind..terawatt.hours.")
energy <- rename(energy, "Solar" = "Solar..terawatt.hours.")
energy <- rename(energy, "Other renewables" = "Other.renewables..modern.biofuels..geothermal..wave...tidal...terawatt.hours.")
energy <- energy[ ,-2]

energy$TotalenergyUse <- rowSums(energy[, c("Hydro", "Wind", "Solar", "Other renewables")], na.rm=T)

energy <- energy[ ,-3:-6]

#Lager plot for energy world


worldenergy <- energy %>%
  filter(Country == "World")

ggplot(worldenergy, aes(x = Year, y = TotalenergyUse)) +
  geom_line()+
  ggtitle("World energy use")

#Energy Africa

africaenergy <- energy %>%
  filter(Country == "Africa")

ggplot(africaenergy, aes(x = Year, y = TotalenergyUse))+
  geom_line()+
  ggtitle("Africa energy use")

#Energy Europe

europeEnergy <- energy %>%
  filter(Country == "European Union")

ggplot(europeEnergy, aes(x = Year, y = TotalenergyUse))+
  geom_line()+
  ggtitle("European Union energy use")

#Energy Asia

asiaenergy <- energy %>%
  filter(Country == "Asia Pacific")

ggplot(asiaenergy, aes(x = Year, y = TotalenergyUse))+
  geom_line()+
  ggtitle("Asia energy use")

#Energy North America

americaenergy <- energy %>%
  filter(Country == "North America")

ggplot(americaenergy, aes(x = Year, y = TotalenergyUse))+
  geom_line()+
  ggtitle("North America Energy use")

#Energy China

chinaenergy <- energy %>%
  filter(Country == "China")

#Total energy for easy viewing

energyview <- energy



```

```{r}
#Laster opp gdp percap filen og rydder den

GdpPercap <- read.csv("real-gdp-per-capita-PWT.csv")

GdpPercap <- rename(GdpPercap, "Country" = "Entity", "Year" = "Year", "GdpPercap" = "GDP.per.capita..2011.international....PPP.adjusted.US...")

GdpPercap <- GdpPercap[ , -2]

GdpUS <- GdpPercap %>%
  filter(Country == "United States")

ggplot(GdpUS, aes(x = Year, y = GdpPercap)) +
  geom_line() +
  ggtitle("North America GDP per capita")

GdpChina <- GdpPercap %>%
  filter(Country == "China")



#Tester å sette gdppercap med totalenergy use for USA. Kunne startet den lavere og på samme punkt på y aksen, men det er ingen korrelasjon uansett.
ggplot() +
  geom_line(data = GdpUS, aes(y = GdpUS$GdpPercap, x = Year)) +
  geom_line(data = americaenergy, aes(y = americaenergy$TotalenergyUse, x = Year))


```

```{r}
#China alle plots

ggplot(GdpChina, aes(x = Year, y = GdpPercap)) +
  geom_line() +
  ggtitle("China GDP per capita")

ggplot(chinaenergy, aes(x = Year, y = TotalenergyUse))+
  geom_line()+
  ggtitle("China Energy use")

chinahdi <- hdi %>%
  filter(Country == "China")

ggplot(chinahdi, aes(x = Year, y = Value)) +
  geom_line() +
  ggtitle("China HDI")


```

```{r}
#India, for å sjekke om populasjon kan forklare økt bruk av alternativ energi

indiaenergy <- energy %>%
  filter(Country == "India")

ggplot(indiaenergy, aes(x = Year, y = TotalenergyUse)) +
  geom_line() +
  ggtitle("India energy use")

indiaGdp <- GdpPercap %>%
  filter(Country == "India")

ggplot(indiaGdp, aes(x = Year, y = GdpPercap)) +
  geom_line() +
  ggtitle("India GdpPercap")



```


```{r}
# ANIMERT GRAF AV GDP-PER-CAPITA 

gifski_renderer(file = tempfile(fileext = ".gif"), loop = TRUE,
  width = NULL, height = NULL)

file_renderer(dir = ".", prefix = "gganim_plot", overwrite = FALSE)

animplot <- ggplot(GdpPercap, aes(x=Year , y=GdpPercap, color=Country)) + 
  geom_line() + 
  geom_point() + 
  ggtitle("Gdp per capita by country from 1950 to 2018") + 
  ylab("Gdp per capita") +
  transition_reveal(Year)+
  theme_ft_rc()



```

```{r}
#Uploading and fixing the population file for easy data wrangling

Population <- read.csv("population-figures-by-country-csv_csv.csv")

Population <- gather(Population, Year, Population, Year_1960:Year_2016)

Population$Year <- substring(Population$Year, 6, 9)

Population$Year <- as.numeric(Population$Year)

Population <- Population[-1:-1315, ]

Population <- Population [, -2]

#Merging it together with energyview to get Per capita

Totalpop <- merge(Population, energyview)

totalprcap <- Totalpop %>%
  group_by(Year, Country) %>%
  summarise(Prcap = TotalenergyUse/Population)

chinatest <- totalprcap %>%
  filter(Country == "China")

chinapop <- Population %>%
  filter(Country == "China")

chinatotal <- merge(chinaenergy, chinapop)

chinatotal <- chinatotal %>%
  group_by(Year) %>%
  summarise(EnergyprCap = TotalenergyUse/Population)

ggplot(chinatotal, aes(x = Year, y = EnergyprCap)) +
  geom_line()
```

```{r}
#Heads (top5) for each category

Continents <- c("Non-OECD", "World", "OECD", "Asia Pacific", "Europe & Eurasia", "North America", "European Union", "South & Central America", "CIS")

#Fixing for 2016 on prcap energyuse
prcap2016 <- totalprcap %>%
  filter(Year == 2016)


Headprcap <- prcap2016[order(-prcap2016$Prcap), ]
head(unique(Headprcap$Country, 5))

#Removing continents for energyview. usinc c() didnt work so i had to force it.
energy2016 <- energyview %>%
  filter(Year == 2016)

energyview <- energyview %>%
  filter(Country != "Non-OECD") %>%
  filter(Country != "World") %>%
  filter(Country != "OECD") %>%
  filter(Country != "Asia Pacific") %>%
  filter(Country != "Europe & Eurasia") %>%
  filter(Country != "North America") %>%
  filter(Country != "European Union") %>%
  filter(Country != "South & Central America") %>%
  filter(Country != "CIS") %>%
  filter(Country != "Africa")

#Top 5 Total energy use 2016
Headtotal <- energy2016[order(-energy2016$TotalenergyUse), ] 
head(unique(Headtotal$Country, 5))

```

```{r}
#Growth rate energyprcap function

growth <- function(x){(x/lag(x)-1)}

totalprcap <- totalprcap %>%
  filter(Country != "World")

rateprcap <- totalprcap %>%
  group_by(Country) %>%
  mutate_each(funs(growth), Prcap)

rateprcap <- rateprcap[-1:-54, ]

#Average growth rate, divided by 50 [(2016-1965)-1]

avgGrowth <- rateprcap %>%
  group_by(Country) %>%
  summarise(AvgGrowth = sum(Prcap/50))
  
  
ratetotal <- energyview %>%
  group_by(Country) %>%
  mutate_each(funs(growth), TotalenergyUse)

ratetotal <- na.omit(ratetotal)

Avgtotal <- ratetotal %>%
  group_by(Country) %>%
  summarise(AvGrowth = sum(TotalenergyUse/50))

#First 5 for rates cap and total

Headratecap <- rateprcap[order(-rateprcap$Prcap), ]
head(unique(Headratecap$Country, 5))

Headtotalcap <- ratetotal[order(-ratetotal$TotalenergyUse), ]
head(unique(Headtotalcap$Country, 5))
```


```{r}
#Interactive plot for total energy use
plotTotal <- energyview %>%
  SharedData$new(key = ~Country, group = "Select a country") %>%
  plot_ly(x = ~Year, y = ~TotalenergyUse, alpha = 0.5, hoverinfo = "text", text = ~Country) %>%
  group_by(Country) %>%
  add_lines() %>%
  highlight(selectize = TRUE)
plotTotal
```

```{r}
#Plot for energy pr capita
plotPrcap <- totalprcap %>%
  SharedData$new(key = ~Country, group = "Select a country") %>%
  plot_ly(x = ~Year, y = ~Prcap, alpha = 0.5, hoverinfo = "text", text = ~Country) %>%
  group_by(Country) %>%
  add_lines() %>%
  highlight(selectize = TRUE)

plotPrcap
```



